# Generated by Django 4.1.7 on 2023-04-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('T_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=100)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.teacher')),
            ],
        ),
    ]
